# Introduction to APIs

## 1.&nbsp; Recap: lists and dictionaries

### 1.1&nbsp;Lists

A list starts and ends with square brackets `[]` and contains elements that are separated with a comma `,`.

Here are a few examples:

In [1]:
# Empty list.
empty_list = []
empty_list

[]

In [2]:
# List containing numbers.
list_with_numbers = [2, 64, 3.5, 7392, -5]
list_with_numbers

[2, 64, 3.5, 7392, -5]

In [3]:
# List containing other lists as elements.
list_of_lists = [[1, 2, 3], ["apples", 280], [-1, True, 4.5]]
list_of_lists

[[1, 2, 3], ['apples', 280], [-1, True, 4.5]]

You can access the individual elements inside the list by using their index.

In [6]:
# Get the first element from the list_with_numbers.
list_with_numbers[0]

2

In [7]:
# Get the second element from the list_of_lists.
list_of_lists[1]

['apples', 280]

In [8]:
# Get the first element from the second list inside the list of lists.
list_of_lists[1][0]

'apples'

### 1.2&nbsp;Dictionaries

A dictionary starts and ends with curly brackets `{}` and contains key-value pairs which are separated by a comma `,`.

Here are a few examples:

In [9]:
# Empty dictionary.
empty_dictionary = {}
empty_dictionary

{}

In [10]:
# Simple dictionary.
simple_dictionary = {"surname": "Duck", "name": "Donald"}
simple_dictionary

{'surname': 'Duck', 'name': 'Donald'}

You can get a list with all the keys of the dictionary using `.keys()`.

In [12]:
# Show the keys inside the dictionary.
simple_dictionary.keys()

dict_keys(['surname', 'name'])

You can access the individual values inside the dictionary by using the name of the key.

In [13]:
# Get the value of the key "name".
simple_dictionary["name"]

'Donald'

In [14]:
# Nested dictionary that contains another dictionary as one of the values.
nested_dictionary = {"surname": "Holmes", "name": "Sherlock", "address": {"street": "Baker Street 221b", "city": "London"}}
nested_dictionary

{'surname': 'Holmes',
 'name': 'Sherlock',
 'address': {'street': 'Baker Street 221b', 'city': 'London'}}

In [15]:
# This also works with nested dictionaries.
nested_dictionary["address"]

{'street': 'Baker Street 221b', 'city': 'London'}

In [16]:
# Combinations are also possible.
nested_dictionary["address"].keys()

dict_keys(['street', 'city'])

In [17]:
nested_dictionary["address"]["street"]

'Baker Street 221b'

In [21]:
nested_dictionary.get("surname") is nested_dictionary["surname"]

True

In [24]:
# nested_dictionary["last_name"]
nested_dictionary.get("last_name") is None

True

In [32]:
nested_dictionary.get("last_name", {})

{}

In [26]:
nested_dictionary.get("address").get("street") is nested_dictionary["address"]["street"]

True

In [27]:
nested_dictionary.keys()

dict_keys(['surname', 'name', 'address'])

In [28]:
simple_dictionary.keys()

dict_keys(['surname', 'name'])

In [29]:
characters = [simple_dictionary, nested_dictionary]

In [33]:
# for character in characters:
#     print(character["address"]["street"])

for character in characters:
    print(character.get("address", {}).get("street"))

None
Baker Street 221b

## 2.&nbsp;Requests

The requests library is the de facto standard for making HTTP requests in Python. It abstracts the complexities of making requests behind a beautiful, simple API so that you can focus on interacting with services and consuming data in your application.

https://requests.readthedocs.io/en/latest/

When we make a request, we get a `requests.Response` object in return. The `requests.Response` object contains the server's response to the HTTP request. The response itself consists of several parts such as the content, the text or the status code.

The status code is a number that tells us whether we received the information we wanted or not. If you get a number that you don't understand, these cats will help you: https://http.cat/.

More often than not you'll receive one of these status codes:

- `200`: Success!

- `401`: Unauthorized client error status: lack of valid authentication credentials

- `403`: The server understood the request but refuses to authorize it

In [34]:
import pandas as pd
import requests

Make a request to the website of The New York Times.

In [35]:
# The response from the website is stored inside the variable 'nyt'.
nyt = requests.get("https://www.nytimes.com/")
nyt

In [37]:
# Get the status code from the response.
nyt.status_code == 200

True

In [38]:
dir(nyt)

['__attrs__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_content',
 '_content_consumed',
 '_next',
 'apparent_encoding',
 'close',
 'connection',
 'content',
 'cookies',
 'elapsed',
 'encoding',
 'headers',
 'history',
 'is_permanent_redirect',
 'is_redirect',
 'iter_content',
 'iter_lines',
 'json',
 'links',
 'next',
 'ok',
 'raise_for_status',
 'raw',
 'reason',
 'request',
 'status_code',
 'text',
 'url']

In [39]:
# Get the text from the response.
nyt.text

'<!DOCTYPE html>\n<html lang="en" class=" nytapp-vi-homepage "  data-nyt-compute-assignment="fallback" xmlns:og="http://opengraphprotocol.org/schema/">\n  <head>\n    \n    \n    <meta charset="utf-8" />\n    <title data-rh="true">The New York Times - Breaking News, US News, World News and Videos</title>\n    <meta data-rh="true" name="description" content="Live news, investigations, opinion, photos and video by the journalists of The New York Times from more than 150 countries around the world. Subscribe for coverage of U.S. and international news, politics, business, technology, science, health, arts, sports and more."/><meta data-rh="true" property="og:url" content="https://www.nytimes.com"/><meta data-rh="true" property="og:type" content="website"/><meta data-rh="true" property="og:title" content="The New York Times - Breaking News, US News, World News and Videos"/><meta data-rh="true" property="og:description" content="Live news, investigations, opinion, photos and video by the journalists of The New York Times from more than 150 countries around the world. Subscribe for coverage of U.S. and international news, politics, business, technology, science, health, arts, sports and more."/><meta data-rh="true" property="og:image" content="https://static01.nyt.com/newsgraphics/images/icons/defaultPromoCrop.png"/> <link data-rh="true" rel="canonical" href="https://www.nytimes.com"/><link data-rh="true" rel="alternate" href="https://www.nytimes.com" hrefLang="x-default"/><link data-rh="true" rel="alternate" href="https://www.nytimes.com" hrefLang="en-US"/><link data-rh="true" rel="alternate" href="https://www.nytimes.com/international/" hrefLang="en"/><link data-rh="true" rel="alternate" href="https://www.nytimes.com/international/" hrefLang="en-GB"/><link data-rh="true" rel="alternate" href="https://www.nytimes.com/international/" hrefLang="en-AU"/><link data-rh="true" rel="alternate" href="https://www.nytimes.com/ca/" hrefLang="en-CA"/><link data-rh="true" rel="alternate" href="https://www.nytimes.com/es/" hrefLang="es"/><link data-rh="true" rel="alternate" href="https://cn.nytimes.com" hrefLang="zh-Hans"/><link data-rh="true" rel="alternate" href="https://cn.nytimes.com/zh-hant/" hrefLang="zh-Hant"/><link data-rh="true" rel="alternate" type="application/rss+xml" title="RSS" href="https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"/> <script data-rh="true" type="application/ld+json">{"@context":"https://schema.org","@type":"WebSite","image":[{"@context":"https://schema.org","@type":"ImageObject","url":"https://static01.nyt.com/vi-assets/images/share/1200x675_nameplate.png","height":675,"width":1200,"contentUrl":"https://static01.nyt.com/vi-assets/images/share/1200x675_nameplate.png","creditText":"The New York Times"},{"@context":"https://schema.org","@type":"ImageObject","url":"https://static01.nyt.com/vi-assets/images/share/1200x900_t.png","height":900,"width":1200,"contentUrl":"https://static01.nyt.com/vi-assets/images/share/1200x900_t.png","creditText":"The New York Times"},{"@context":"https://schema.org","@type":"ImageObject","url":"https://static01.nyt.com/vi-assets/images/share/1200x1200_t.png","height":1200,"width":1200,"contentUrl":"https://static01.nyt.com/vi-assets/images/share/1200x1200_t.png","creditText":"The New York Times"}],"url":"https://www.nytimes.com","name":"The New York Times","alternateName":["NYT","new york times","nytimes","ny times"],"potentialAction":{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.nytimes.com/search?query={search_term_string}"},"query-input":"required name=search_term_string"},"mainEntity":{"@context":"https://schema.org","@type":"ItemList","itemListElement":[{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/us/politics/undocumented-immigrants-aid-texas-floods.html","position":1},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/us/politics/trump-fbi-patrol-washington.html","position":2},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/us/politics/harvard-trump-may-mailman.html","position":3},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/us/politics/ohio-maha-moms-farms.html","position":4},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/health/kennedy-vaccine-court.html","position":5},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/us/politics/jd-vance-zelensky-trump-putin.html","position":6},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/world/middleeast/israel-gaza-journalists-killed.html","position":7},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/world/australia/australia-palestine-statehood.html","position":8},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/business/china-electric-vehicles-red-sea.html","position":9},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/us/mark-zuckerberg-palo-alto.html","position":10},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/world/asia/india-migrants-raids-muslims-bengalis.html","position":11},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/world/asia/book-ban-india-kashmir.html","position":12},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/athletic/6540504/2025/08/07/stephen-nedoroscik-olympics-pommel-horse-gymnastics-championships/","position":13},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/08/realestate/bears-romania.html","position":14},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/style/alyson-stoner-memoir-disney-nickelodeon.html","position":15},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/opinion/sydney-sweeney-secret.html","position":16},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/opinion/cdc-shooting-vaccine-misinformation.html","position":17},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/opinion/america-short-term-thinking.html","position":18},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/opinion/alexandria-ocasio-cortez-deepfake-ai.html","position":19},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/us/california-redistricting-independent-commission.html","position":20},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/world/europe/earthquake-western-turkey-sindirgi.html","position":21},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/11/business/aol-dial-up-internet.html","position":22},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/2025/08/10/arts/music/terry-reid-dead.html","position":23},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/athletic/connections-sports-edition","position":24},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/games/wordle/index.html","position":25},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/games/connections?GAMES_connectionsRollout_1130=1_ConnectionsV2","position":26},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/games/strands","position":27},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/puzzles/spelling-bee","position":28},{"@context":"https://schema.org","@type":"ListItem","url":"https://www.nytimes.com/crosswords","position":29},{"@context":"https://schema.org","@type":"ListItem","url":"http://www.nytimes.com/crosswords/game/mini","position":30}],"numberOfItems":30},"publisher":{"@id":"https://www.nytimes.com/#publisher","name":"The New York Times"}}</script><script data-rh="true" type="application/ld+json">{"@context":"https://schema.org","@type":"NewsMediaOrganization","name":"The New York Times","logo":{"@context":"https://schema.org","@type":"ImageObject","url":"https://static01.nyt.com/images/icons/t_logo_291_black.png","height":291,"width":291,"contentUrl":"https://static01.nyt.com/images/icons/t_logo_291_black.png","creditText":"The New York Times"},"url":"https://www.nytimes.com/","@id":"https://www.nytimes.com/#publisher","publishingPrinciples":"https://www.nytimes.com/editorial-standards/ethical-journalism.html","diversityPolicy":"https://www.nytco.com/company/diversity-and-inclusion/","ethicsPolicy":"https://www.nytco.com/company/standards-ethics/","masthead":"https://www.nytimes.com/interactive/2023/01/28/admin/the-new-york-times-masthead.html","foundingDate":"1851-09-18","sameAs":["https://www.facebook.com/nytimes/","https://x.com/nytimes","https://www.instagram.com/nytimes/","https://www.youtube.com/user/TheNewYorkTimes","https://www.linkedin.com/company/the-new-york-times","https://www.wikidata.org/wiki/Q9684","https://en.wikipedia.org/wiki/The_New_York_Times"],"alternateName":["NYT","new york times","nytimes","ny times"],"subOrganization":[{"@type":"Organization","name":"NYT Cooking","url":"https://cooking.nytimes.com/","sameAs":["https://www.facebook.com/nytcooking/","https://www.facebook.com/groups/nytcooks/","https://www.instagram.com/nytcooking/","https://www.youtube.com/channel/UC1rIOwTqDuWkFj87HZYRFOg","https://x.com/nytfood"],"logo":[{"url":"https://static01.nyt.com/applications/cooking/37f1abc/assets/SiteLogoRed.svg","height":31,"width":168,"@type":"ImageObject"},{"url":"https://static01.nyt.com/applications/cooking/37f1abc/assets/SiteLogoBlack.svg","height":24,"width":131,"@type":"ImageObject"}]},{"@type":"Organization","name":"Wirecutter","url":"https://www.nytimes.com/wirecutter/","sameAs":["https://www.facebook.com/thewirecutter/","https://www.instagram.com/wirecutter/","https://x.com/wirecutter/","https://www.linkedin.com/company/the-wirecutter/","https://www.youtube.com/wirecutter"],"logo":{"@type":"ImageObject","url":"https://cdn.thewirecutter.com/wp-content/uploads/2020/05/nytimes-wirecutter-logo.png","width":266,"height":34}},{"@type":"Organization","name":"The Athletic","url":"https://www.nytimes.com/athletic/","sameAs":["https://www.facebook.com/TheAthletic","https://instagram.com/TheAthleticHQ","https://x.com/TheAthletic","https://www.linkedin.com/company/the-athletic-media-company/","https://www.youtube.com/TheAthletic"],"logo":{"@type":"ImageObject","url":"https://www.nytimes.com/athletic/app/themes/athletic/assets/img/open-graph-asset.png","width":266,"height":150}}]}</script>\n    <meta data-rh="true" name="application-name" content="The New York Times"/><meta data-rh="true" name="msapplication-starturl" content="https://www.nytimes.com"/><meta data-rh="true" name="msapplication-task" content="name=Search;action-uri=https://www.nytimes.com/search/?src=iepin;icon-uri=https://static01.nyt.com/images/icons/search.ico"/><meta data-rh="true" name="msapplication-task" content="name=Most Popular;action-uri=https://www.nytimes.com/trending/?src=iepin;icon-uri=https://static01.nyt.com/images/icons/mostpopular.ico"/><meta data-rh="true" name="msapplication-task" content="name=Video;action-uri=https://www.nytimes.com/video?src=iepin;icon-uri=https://static01.nyt.com/images/icons/video.ico"/><meta data-rh="true" name="msapplication-task" content="name=Homepage;action-uri=https://www.nytimes.com?src=iepin&amp;adxnnl=1;icon-uri=https://static01.nyt.com/images/icons/homepage.ico"/><meta data-rh="true" name="nyt_uri" content="nyt://programmingnode/1999c500-b740-5ba9-b2c1-57ff6b183315"/><meta data-rh="true" name="CG" content="Homepage"/><meta data-rh="true" name="SCG" content=""/><meta data-rh="true" name="PT" content="Homepage"/><meta data-rh="true" name="PST" content=""/><meta data-rh="true" name="keywords" content="news, live updates, latest news, breaking news, local news, current events, top stories, livestream, live video, world news, us news"/>\n    \n<meta name="viewport" content="width=device-width, initial-scale=1" />\n<meta property="fb:app_id" content="9869919170" />\n<meta name="twitter:site" content="@nytimes" />\n<meta name="slack-app-id" content="A0121HXPPTQ" />\n    <script>(function Ft(e){if(new URL(window.location).searchParams.get("sentryOverride")||Math.floor(100*Math.random())<=e){var n=[\'<script src="https://js.sentry-cdn.com/7bc8bccf5c254286a99b11c68f6bf4ce.min.js" crossorigin="anonymous">\',"<","/script>"].join("");document.write(n)}})(1);</script><script>(function Jt(e){var n=e.release,t=e.env,a=e.routeName,i=window.vi&&window.vi.webviewEnvironment||{},o=i.isPreloaded,r=void 0!==o&&o,l="IOS"===i.deviceType;if(window.Sentry){var s=function(){window.Sentry.init({maxBreadcrumbs:c,release:n,environment:t,allowUrls:u,ignoreErrors:d,beforeSend:function(e,n){var t=n.originalException;return t&&t.stack&&t.stack.includes("datadog-rum")?null:e},initialScope:function(e){e.setTags({"nyt.route":a});var n=/nyt-a=(.*?)(;|$)/.exec(document.cookie);null!==n&&e.setUser({id:n[1]});try{if(r){var t,i,o=window.asset||{},s=o.eventId,c=void 0===s?"":s,d=o.uri,u=void 0===d?"":d,f=o.url,p=void 0===f?"":f,m=o.sourceType,g=void 0===m?"":m,h=o.sourceId,v=void 0===h?"":h;c&&e.setTag("eventId",c),u&&e.setTag("uri",u),p&&e.setTag("url",p),g&&e.setTag("sourceType",g),v&&e.setTag("sourceId",v),e.setExtra("visibilityState",document.visibilityState),null!==(t=window)&&void 0!==t&&null!==(i=t.performance)&&void 0!==i&&i.timeOrigin&&e.setExtra("timeOrigin",window.performance.timeOrigin),e.setTag("type","preloaded-webview")}else e.setTag("type","browser");var b=function(){var n=window.config||{},t=n.AppVersion,a=void 0===t?"":t,i=n.ConnectionStatus,o=void 0===i?3:i,r=n.LoggedIn,l=void 0!==r&&r,s=n.Subscriber,c=void 0!==s&&s;null==e||e.setTag("AppVersion",a),null==e||e.setTag("ConnectionStatus",o),null==e||e.setTag("LoggedIn",l),null==e||e.setTag("Subscriber",c)};l?window.addEventListener("initWebview:ios",b):b()}catch(e){console.error(e)}return e},replaysSessionSampleRate:0,replaysOnErrorSampleRate:.01,integrations:[window.Sentry.browserTracingIntegration({enableInp:!0,instrumentNavigation:!1,instrumentPageLoad:!1})]});var e=window.Sentry.getClient(),i={};i[window.Sentry.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE]="url",window.Sentry.startBrowserTracingPageLoadSpan(e,{name:a,attributes:i})},c=70,d=["2mdn","ads-us","amazon-adsystem","amp4ads","ampproject","bk_addPageCtx","boomerang","BOOMR","cb is not a function","chartbeat","google_tag_manager","gsi","gtm","prebid","pubads","scorecardresearch","setConfig is not a function","webkitExitFullScreen","yimg","reading \'campaign\'","Object.fromEntries is not a function"];r&&(d=d.concat(["Failed to fetch","Load failed","Something went wrong","Unexpected EOF","The request is not allowed by the user agent","scrollIntoView","No weather-bot homepage data available","UnhandledRejection: Non-Error promise rejection captured with value: false","VHS is currently showing this error message on-screen.","useMessageSelection","messageComponentLibrary"]));var u=[/^https?:\\/\\/(vi-pr-.*|www|vi|local|alpha|alpha-preview)\\.(stg\\.|dev\\.)?(nytimes\\.com|nyt\\.net)/];window.Sentry.onLoad(s),window.__isUnitTestEnv&&(window.__testSentryOnload=s)}})({"release":"d36491a1014d170f2dd31368a053ad587591a30d","env":"prd","routeName":"homepage","allowUrls":[{}]});</script>\n    \n    <script>\n      (function Vt(){var e,n,t,a,i;e=window,n=document,t="script",a="https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js",e=e[i="DD_RUM"]=e[i]||{q:[],onReady:function(n){e.q.push(n)}},(i=n.createElement(t)).async=1,i.src=a,(a=n.getElementsByTagName(t)[0]).parentNode.insertBefore(i,a)})();\n      (function Gt(e){var n=e.service,t=e.env,a=e.version,i=e.sessionSampleRate,o=e.deploymentId,r=e.routeName,l=e.tenant;if(window.DD_RUM){var s=function(){var e={clientToken:"pube5bf68ea68edb54c35106f34e32ff07c",applicationId:"7d0602a0-8ef8-4d39-985b-c3188887e5b3",site:"datadoghq.com",service:"".concat(n,"-client"),env:t,version:a,sessionSampleRate:parseInt(i,10),sessionReplaySampleRate:v,trackUserInteractions:!0,trackResources:!0,trackLongTasks:!0,trackViewsManually:!0,defaultPrivacyLevel:"mask-user-input",allowedTracingUrls:m,traceSampleRate:10,traceContextInjection:"sampled",useCrossSiteSessionCookie:!0,useSecureSessionCookie:!0};u&&(e=Object.assign(e,h)),window.DD_RUM.init(e);var s="web";u&&(s=window.config&&window.config.OS&&"ANDROID"===window.config.OS.toUpperCase()?"android":"ios");var c={billing:{environment:t,deployment:{id:o}},dvsp:{tenant:l},route:{name:r},webview:p,preloaded:u,appType:s};u&&(c=Object.assign(c,g)),window.DD_RUM.setGlobalContextProperty("nyt",c),window.DD_RUM.startView({name:r});var d=/nyt-a=(.*?)(;|$)/.exec(document.cookie);if(null!==d&&window.DD_RUM.setUser({id:d[1]}),u){var f=(window.asset||{}).url,b=void 0===f?"":f;window.DD_RUM.setGlobalContextProperty("url",b);var y=window.getNativeBridgeCookie("nyt-a");y&&window.DD_RUM.setUser({id:y})}},c=window.vi&&window.vi.webviewEnvironment||{},d=c.isPreloaded,u=void 0!==d&&d,f=c.isInWebview,p=void 0!==f&&f,m=[/https:\\/\\/samizdat-graphql.*\\.nytimes\\.com/,/https:\\/\\/alpha\\.nytimes\\.com/,/https:\\/\\/www\\.nytimes\\.com/,/https:\\/\\/www\\.stg\\.nytimes\\.com/,/https:\\/\\/cooking\\.nytimes\\.com/,/https:\\/\\/myaccount\\.nytimes\\.com/],g={},h={},v=10;u&&(g={team:"web-platforms"},v=0,h={trackFrustrations:!0,allowFallbackToLocalStorage:!0}),window.DD_RUM.onReady(s),window.__isUnitTestEnv&&(window.__testDataDogOnReady=s)}})({"service":"vi","env":"prd","version":"vi-newsreader@v8043-d36491a","sessionSampleRate":"10","deploymentId":"aws-491988406224","routeName":"homepage","tenant":"web-platforms"});\n    </script>\n  \n\n    <link data-rh="true" rel="shortcut icon" href="/vi-assets/static-assets/favicon-d2483f10ef688e6f89e23806b9700298.ico"/><link data-rh="true" rel="apple-touch-icon" href="/vi-assets/static-assets/apple-touch-icon-28865b72953380a40aa43318108876cb.png"/><link data-rh="true" rel="apple-touch-icon-precomposed" sizes="144×144" href="/vi-assets/static-assets/ios-ipad-144x144-28865b72953380a40aa43318108876cb.png"/><link data-rh="true" rel="apple-touch-icon-precomposed" sizes="114×114" href="/vi-assets/static-assets/ios-iphone-114x144-080e7ec6514fdc62bcbb7966d9b257d2.png"/><link data-rh="true" rel="apple-touch-icon-precomposed" href="/vi-assets/static-assets/ios-default-homescreen-57x57-43808a4cd5333b648057a01624d84960.png"/><link data-rh="true" rel="preload" href="https://static01.nyt.com/video-static/betamax/player-0.1.46-xirwFYnl.css" as="style" crossorigin=""/><link data-rh="true" rel="modulepreload" href="https://static01.nyt.com/video-static/betamax/player-0.1.46-DEBXIFF_.js" as="script" crossorigin=""/><link data-rh="true" rel="modulepreload" href="https://static01.nyt.com/video-static/betamax/video-element-BhCJxP7P.js" as="script" crossorigin=""/><link data-rh="true" rel="modulepreload" href="https://static01.nyt.com/video-static/betamax/identify-user-NlIHKxju.js" as="script" crossorigin=""/><link data-rh="true" rel="preload" href="https://static01.nyt.com/video-static/betamax/overlay-controls-0.1.46-CQrUOMqt.css" as="style" crossorigin=""/><link data-rh="true" rel="preload" href="https://static01.nyt.com/video-static/betamax/scrubber-0.1.46-BdHXhxJd.css" as="style" crossorigin=""/><link data-rh="true" rel="modulepreload" href="https://static01.nyt.com/video-static/betamax/overlay-controls-0.1.46-CJXjrkrz.js" as="script" crossorigin=""/><link data-rh="true" rel="modulepreload" href="https://static01.nyt.com/video-static/betamax/scrubber-Y18rIaGd

Make a request to the website of WBS Coding School.

In [ ]:
# The response from the website is stored inside the variable 'wbscs'.
wbscs = requests.get("https://www.wbscodingschool.com/")
wbscs

In [ ]:
wbscs.status_code

200

In [ ]:
wbscs.text

'<!doctype html><html lang="en-US" prefix="og: https://ogp.me/ns#"><head><style type="text/css" id="wpc-critical-css" class="wpc-critical-css-desktop">:root{--wp--preset--aspect-ratio--square: 1;--wp--preset--aspect-ratio--4-3: 4/3;--wp--preset--aspect-ratio--3-4: 3/4;--wp--preset--aspect-ratio--3-2: 3/2;--wp--preset--aspect-ratio--2-3: 2/3;--wp--preset--aspect-ratio--16-9: 16/9;--wp--preset--aspect-ratio--9-16: 9/16;--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;--wp--preset--spacing--20: 0.44rem;--wp--preset--spacing--30: 0.67rem;--wp--preset--spacing--40: 1rem;--wp--preset--spacing--50: 1.5rem;--wp--preset--spacing--60: 2.25rem;--wp--preset--spacing--70: 3.38rem;--wp--preset--spacing--80: 5.06rem;--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1)}.wpml-ls-flag{display:inline-block}.wpml-ls-flag{display:inline-block}:root{--map-dialog-top:0px}:focus{outline:0}.wpml-ls-menu-item .wpml-ls-flag{display:inline;vertical-align:baseline}.wpml-ls-menu-item .wpml-ls-flag+span{margin-left:.3em}ul .wpml-ls-menu-item a{display:flex;align-items:center}html{line-height:1.15;-webkit-text-size-adjust:100%}*,:after,:before{box-sizing:border-box}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;font-size:1rem;font-weight:400;line-height:1.5;color:#333;background-color:#fff;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}h1,h2,h3{margin-block-start:.5rem;margin-block-end:1rem;font-family:inherit;font-weight:500;line-height:1.2;color:inherit}h1{font-size:2.5rem}h2{font-size:2rem}h3{font-size:1.75rem}p{margin-block-start:0;margin-block-end:.9rem}a{background-color:transparent;text-decoration:none;color:#c36}a:not([href]):not([tabindex]){color:inherit;text-decoration:none}strong{font-weight:bolder}img{border-style:none;height:auto;max-width:100%}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}li,ul{margin-block-start:0;margin-block-end:0;border:0;outline:0;font-size:100%;vertical-align:baseline;background:transparent}@charset "UTF-8";.screen-reader-text{clip:rect(1px,1px,1px,1px);height:1px;overflow:hidden;position:absolute!important;width:1px;word-wrap:normal!important}@charset "UTF-8";.elementor-screen-only,.screen-reader-text{position:absolute;top:-10000em;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);border:0}.elementor *,.elementor :after,.elementor :before{box-sizing:border-box}.elementor a{box-shadow:none;text-decoration:none}.elementor img{height:auto;max-width:100%;border:none;border-radius:0;box-shadow:none}.elementor .elementor-widget:not(.elementor-widget-text-editor):not(.elementor-widget-theme-post-content) figure{margin:0}.elementor-element{--flex-direction:initial;--flex-wrap:initial;--justify-content:initial;--align-items:initial;--align-content:initial;--gap:initial;--flex-basis:initial;--flex-grow:initial;--flex-shrink:initial;--order:initial;--align-self:initial;flex-basis:var(--flex-basis);flex-grow:var(--flex-grow);flex-shrink:var(--flex-shrink);order:var(--order);align-self:var(--align-self)}.elementor-element:where(.e-con-full,.elementor-widget){flex-direction:var(--flex-direction);flex-wrap:var(--flex-wrap);justify-content:var(--justify-content);align-items:var(--align-items);align-content:var(--align-content);gap:var(--gap)}@media (max-width:767px){.elementor-mobile-align-center{text-align:center}.elementor-mobile-align-center .elementor-button{width:auto}.elementor-mobile-align-left{text-align:left}.elementor-mobile-align-left .elementor-button{width:auto}.elementor-mobile-align-justify .elementor-button{width:100%}}:root{--page-title-display:block}.elementor-widget{position:relative}.elementor-widget:not(:last-child){margin-bottom:20px}.elementor-widget:not(:last-child).elementor-widget__width-initial{margin-bottom:0}@media (prefers-reduced-motion:no-preference){html{scroll-behavior:smooth}}.e-con{--border-radius:0;--border-top-width:0px;--border-right-width:0px;--border-bottom-width:0px;--border-left-width:0px;--border-style:initial;--border-color:initial;--container-widget-width:100%;--container-widget-height:initial;--container-widget-flex-grow:0;--container-widget-align-self:initial;--content-width:min(100%,var(--container-max-width,1140px));--width:100%;--min-height:initial;--height:auto;--text-align:initial;--margin-top:0px;--margin-right:0px;--margin-bottom:0px;--margin-left:0px;--padding-top:var(--container-default-padding-top,10px);--padding-right:var(--container-default-padding-right,10px);--padding-bottom:var(--container-default-padding-bottom,10px);--padding-left:var(--container-default-padding-left,10px);--position:relative;--z-index:revert;--overflow:visible;--gap:var(--widgets-spacing,20px);--overlay-mix-blend-mode:initial;--overlay-opacity:1;--e-con-grid-template-columns:repeat(3,1fr);--e-con-grid-template-rows:repeat(2,1fr);position:var(--position);width:var(--width);min-width:0;min-height:var(--min-height);height:var(--height);border-radius:var(--border-radius);z-index:var(--z-index);overflow:var(--overflow);--flex-wrap-mobile:wrap;margin-block-start:var(--margin-block-start);margin-inline-end:var(--margin-inline-end);margin-block-end:var(--margin-block-end);margin-inline-start:var(--margin-inline-start);padding-inline-start:var(--padding-inline-start);padding-inline-end:var(--padding-inline-end);--margin-block-start:var(--margin-top);--margin-block-end:var(--margin-bottom);--margin-inline-start:var(--margin-left);--margin-inline-end:var(--margin-right);--padding-inline-start:var(--padding-left);--padding-inline-end:var(--padding-right);--padding-block-start:var(--padding-top);--padding-block-end:var(--padding-bottom);--border-block-start-width:var(--border-top-width);--border-block-end-width:var(--border-bottom-width);--border-inline-start-width:var(--border-left-width);--border-inline-end-width:var(--border-right-width)}.e-con.e-flex{--flex-direction:column;--flex-basis:auto;--flex-grow:0;--flex-shrink:1;flex:var(--flex-grow) var(--flex-shrink) var(--flex-basis)}.e-con-full,.e-con>.e-con-inner{text-align:var(--text-align);padding-block-start:var(--padding-block-start);padding-block-end:var(--padding-block-end)}.e-con-full.e-flex,.e-con.e-flex>.e-con-inner{flex-direction:var(--flex-direction)}.e-con,.e-con>.e-con-inner{display:var(--display)}.e-con-boxed.e-flex{flex-direction:column;flex-wrap:nowrap;justify-content:normal;align-items:normal;align-content:normal}.e-con-boxed{text-align:initial;gap:initial}.e-con.e-flex>.e-con-inner{flex-wrap:var(--flex-wrap);justify-content:var(--justify-content);align-items:var(--align-items);align-content:var(--align-content);flex-basis:auto;flex-grow:1;flex-shrink:1;align-self:auto}.e-con>.e-con-inner{gap:var(--gap);width:100%;max-width:var(--content-width);margin:0 auto;padding-inline-start:0;padding-inline-end:0;height:100%}:is(.elementor-section-wrap,[data-elementor-id])>.e-con{--margin-left:auto;--margin-right:auto;max-width:min(100%,var(--width))}.e-con .elementor-widget.elementor-widget{margin-block-end:0}.e-con:before{content:var(--background-overlay);display:block;position:absolute;mix-blend-mode:var(--overlay-mix-blend-mode);opacity:var(--overlay-opacity);border-radius:var(--border-radius);border-style:var(--border-style);border-color:var(--border-color);border-block-start-width:var(--border-block-start-width);border-inline-end-width:var(--border-inline-end-width);border-block-end-width:var(--border-block-end-width);border-inline-start-width:var(--border-inline-start-width);top:calc(0px - var(--border-top-width));left:calc(0px - var(--border-left-width));width:max(100% + var(--border-left-width) + var(--border-right-width),100%);height:max(100% + var(--border-top-width) + var(--border-bottom-width),100%)}.e-con .elementor-widget{min-width:0}.e-con>.e-con-inner>.elementor-widget>.elementor-widget-container,.e-con>.elementor-widget>.elementor-widget-container{height:100%}.e-con.e-con>.e-con-inner>.elementor-widget,.elementor.elementor .e-con>.elementor-widget{max-width:100%}@media (max-width:767px){.e-con.e-flex{--width:100%;--flex-wrap:var(--flex-wrap-mobile)}}.elementor-heading-title{padding:0;margin:0;line-height:1}.elementor-button{display:inline-block;line-height:1;background-color:#69727d;font-size:15px;padding:12px 24px;border-radius:3px;color:#fff;fill:#fff;text-align:center}.elementor-button:visited{color:#fff}.elementor-button-content-wrapper{display:flex;justify-content:center;flex-direction:row;gap:5px}.elementor-button-text{display:inline-block}.elementor-button span{text-decoration:inherit}.elementor-icon{display:inline-block;line-height:1;color:#69727d;font-size:50px;text-align:center}.elementor-icon i,.elementor-icon svg{width:1em;height:1em;position:relative;display:block}.elementor-icon i:before,.elementor-icon svg:before{position:absolute;left:50%;transform:translateX(-50%)}@media (max-width:767px){.elementor .elementor-hidden-mobile{display:none}}@media (min-width:768px) and (max-width:1024px){.elementor .elementor-hidden-tablet{display:none}}@media (min-width:1025px) and (max-width:99999px){.elementor .elementor-hidden-desktop{display:none}}.elementor-kit-9{--e-global-color-primary:#292929;--e-global-color-secondary:#F8485E;--e-global-color-text:#292929;--e-global-color-accent:#6EC1E4;--e-global-color-99a54c6:#6054E8;--e-global-color-b355f10:#FFFFFF;--e-global-color-98dc525:#F9F7F7;--e-global-color-91c9bf1:#F7A400;--e-global-color-e9babfc:#EAE8FD;--e-global-color-a1d4baf:#FFF5E2;--e-global-color-de75c5e:#A5A5A5;--e-global-color-924df3c:#000000;--e-global-typography-primary-font-family:"Inter";--e-global-typography-primary-font-weight:700;--e-global-typography-secondary-font-family:"Inter";--e-global-typography-secondary-font-weight:600;--e-global-typography-text-font-family:"Helvetica";--e-global-typography-text-font-weight:400;--e-global-typography-accent-font-family:"Helvetica";--e-global-typography-accent-font-weight:600;--e-global-typography-6c66df0-font-family:"Inter";--e-global-typography-6c66df0-font-size:50px;--e-global-typography-6c66df0-font-weight:700;--e-global-typography-6c66df0-text-transform:uppercase;--e-global-typography-6c66df0-line-height:1em;--e-global-typography-39a0a1a-font-family:"Inter";--e-global-typography-39a0a1a-font-size:32px;--e-global-typography-39a0a1a-font-weight:700;--e-global-typography-39a0a1a-text-transform:uppercase;--e-global-typography-39a0a1a-line-height:1.4em;--e-global-typography-efab8c5-font-family:"Inter";--e-global-typography-efab8c5-font-size:24px;--e-global-typography-efab8c5-font-weight:700;--e-global-typography-efab8c5-line-height:1.2em;--e-global-typography-70b14eb-font-family:"Inter";--e-global-typography-70b14eb-font-size:20px;--e-global-typography-70b14eb-font-weight:700;--e-global-typography-70b14eb-line-height:1.6rem;--e-global-typography-87b8f07-font-family:"Inter";--e-global-typography-87b8f07-font-size:16px;--e-global-typography-87b8f07-font-weight:700;color:#292929;font-family:var(--e-global-typography-text-font-family),Sans-serif;font-weight:var(--e-global-typography-text-font-weight)}.elementor-kit-9 a{color:var(--e-global-color-text);font-family:"Helvetica",Sans-serif;font-weight:700;text-decoration:none}.elementor-kit-9 h1{color:var(--e-global-color-text);font-family:var(--e-global-typography-6c66df0-font-family),Sans-serif;font-size:var(--e-global-typography-6c66df0-font-size);font-weight:var(--e-global-typography-6c66df0-font-weight);text-transform:var(--e-global-typography-6c66df0-text-transform);line-height:var(--e-global-typography-6c66df0-line-height);letter-spacing:var(--e-global-typography-6c66df0-letter-spacing);word-spacing:var(--e-global-typography-6c66df0-word-spacing)}.elementor-kit-9 h2{color:var(--e-global-color-text);font-family:var(--e-global-typography-39a0a1a-font-family),Sans-serif;font-size:var(--e-global-typography-39a0a1a-font-size);font-weight:var(--e-global-typography-39a0a1a-font-weight);text-transform:var(--e-global-typography-39a0a1a-text-transform);line-height:var(--e-global-typography-39a0a1a-line-height);letter-spacing:var(--e-global-typography-39a0a1a-letter-spacing);word-spacing:var(--e-global-typography-39a0a1a-word-spacing)}.elementor-kit-9 h3{color:var(--e-global-color-text);font-family:var(--e-global-typography-efab8c5-font-family),Sans-serif;font-size:var(--e-global-typography-efab8c5-font-size);font-weight:var(--e-global-typography-efab8c5-font-weight);line-height:var(--e-global-typography-efab8c5-line-height);letter-spacing:var(--e-global-typography-efab8c5-letter-spacing);word-spacing:var(--e-global-typography-efab8c5-word-spacing)}.elementor-kit-9 .elementor-button{font-family:var(--e-global-typography-87b8f07-font-family),Sans-serif;font-size:var(--e-global-typography-87b8f07-font-size);font-weight:var(--e-global-typography-87b8f07-font-weight);line-height:var(--e-global-typography-87b8f07-line-height);letter-spacing:var(--e-global-typography-87b8f07-letter-spacing);word-spacing:var(--e-global-typography-87b8f07-word-spacing);color:var(--e-global-color-b355f10);background-color:var(--e-global-color-primary);border-style:solid;border-width:2px 2px 2px 2px;border-color:var(--e-global-color-primary);border-radius:100em 100em 100em 100em}.e-con{--container-max-width:1140px}.elementor-widget:not(:last-child){margin-block-end:20px}.elementor-element{--widgets-spacing:20px 20px}@media (max-width:1024px){.elementor-kit-9{--e-global-typography-6c66df0-font-size:43px;--e-global-typography-6c66df0-line-height:1em;--e-global-typography-39a0a1a-font-size:30px;--e-global-typography-39a0a1a-line-height:1.3em;--e-global-typography-70b14eb-font-size:18px}.elementor-kit-9 h1{font-size:var(--e-global-typography-6c66df0-font-size);line-height:var(--e-global-typography-6c66df0-line-height);letter-spacing:var(--e-global-typography-6c66df0-letter-spacing);word-spacing:var(--e-global-typography-6c66df0-word-spacing)}.elementor-kit-9 h2{font-size:var(--e-global-typography-39a0a1a-font-size);line-height:var(--e-global-typography-39a0a1a-line-height);letter-spacing:var(--e-global-typography-39a0a1a-letter-spacing);word-spacing:var(--e-global-typography-39a0a1a-word-spacing)}.elementor-kit-9 h3{font-size:var(--e-global-typography-efab8c5-font-size);line-height:var(--e-global-typography-efab8c5-line-height);letter-spacing:var(--e-global-typography-efab8c5-letter-spacing);word-spacing:var(--e-global-typography-efab8c5-word-spacing)}.elementor-kit-9 .elementor-button{font-size:var(--e-global-typography-87b8f07-font-size);line-height:var(--e-global-typography-87b8f07-line-height);letter-spacing:var(--e-global-typography-87b8f07-letter-spacing);word-spacing:var(--e-global-typography-87b8f07-word-spacing)}.e-con{--container-max-width:1024px}}@media (max-width:767px){.elementor-kit-9{--e-global-typography-6c66df0-font-size:40px;--e-global-typography-6c66df0-line-height:1em;--e-global-typography-39a0a1a-font-size:30px;--e-global-typography-39a0a1a-line-height:1.15em}.elementor-kit-9 h1{font-size:var(--e-global-typography-6c66df0-font-size);line-height:var(--e-global-typography-6c66df0-line-height);letter-spacing:var(--e-global-typography-6c66df0-letter-spacing);word-spacing:var(--e-global-typography-6c66df0-word-spacing)}.elementor-kit-9 h2{font-size:var(--e-global-typography-39a0a1a-font-size);line-height:var(--e-global-typography-39a0a1a-line-height);letter-spacing:var(--e-global-typography-39a0a1a-letter-spacing);word-spacing:var(--e-global-typography-39a0a1a-word-spacing)}.elementor-kit-9 h3{font-size:var(--e-global-typography-efab8c5-font-size);line-height:var(--e-global-typography-efab8c5-line-height);letter-spacing:var(--e-global-typography-efab8c5-letter-spacing);word-spacing:var(--e-global-typography-efab8c5-word-spacing)}.elementor-kit-9 .elementor-button{font-size:var(--e-global-typography-87b8f07-font-size);line-height:var(--e-global-typography-87b8f07-line-height);letter-spacing:var(--e-global-typography-87b8f07-letter-spacing);word-spacing:var(--e-global-typography-87b8f07-word-spacing)}.e-con{--container-max-width:767px}}@font-face{font-display:swap;font-family:eicons;src:url("https://www.wbscodingschool.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.eot?5.31.0");src:url("https://www.wbscodingschool.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.eot?5.31.0#iefix") format("embedded-opentype"),url("https://www.wbscodingschool.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.31.0") format("woff2"),url("https://www.wbscodingschool.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff?5.31.0") format("woff"),url("https://www.wbscodingschool.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.ttf?5.31.0") format("truetype"),url("https://www.wbscodingschool.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.svg?5.31.0#eicon") format("svg");font-weight:400;font-style:normal}[class*=" eicon-"]{display:inline-block;font-family:eicons;font-size:inherit;font-weight:400;font-style:normal;font-variant:normal;line-height:1;text-rendering:auto;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.eicon-menu-bar:before{content:"\\e816"}.eicon-close:before{content:"\\e87f"}:root{--swiper-theme-color:#007aff}.swiper{margin-left:auto;margin-right:auto;position:relative;overflow:hidden;list-style:none;padding:0;z-index:1}.swiper-wrapper{position:relative;width:100%;height:100%;z-index:1;display:flex;box-sizing:content-box}.swiper-wrapper{transform:translate3d(0p

## 3.&nbsp;JSON

### 3.1&nbsp;Viewing the JSON

https://docs.python.org/3/library/json.html

Since its inception, JSON has quickly become the de facto standard for information exchange. JSON supports primitive types, like strings and numbers, as well as nested lists and objects. It looks like nested python dictionaries:

```
{"firstname": "Harry",
 "lastname": "Noah",
 "city": "Berlin",
 "dogs": [{"name": "rover",
   "breed": "labrador"},
   {"name": "pip",
   "breed": "spaniel"}],
 "cars": "none"}
```

Send a `get` request to the International Space Station API to know where the ISS is right now.

You can find the documentation here: http://open-notify.org/Open-Notify-API/ISS-Location-Now/.

In [40]:
# Make a request to the ISS API and store the response in `iss`.
iss = requests.get("http://api.open-notify.org/iss-now.json")

In [41]:
# Check the response.
iss

In [42]:
# Have a look at the text of the response.
text = iss.text
type(text)

str

In [45]:
# Finally: view the response as a JSON.
iss.json().get('iss_position').get('latitude')

'-40.6969'

### 3.2&nbsp;Accessing the data in the JSON

Now that we know
- what an API is,
- how to request information from one (requests),
- how the information will be delivered to us (JSON):

Let's see how we can use this information. We will first look at how we can access particular values within the JSON.

The following API returns the current sunrise and sunset times for a specified location. You can check out the website with the documentation here: https://sunrisesunset.io/api/.

The structure of the url to the API is determined by the provider of the API and usually consists of several parts:

* A first part that leads to the specific API and is the same in every call.
  
  Example: `api.sunrise-sunset.org/json?`

* A mandatory part in which we define certain parameters in a pre-defined format.

  Example: the API requires both the latitude and the longitude of the location in decimal degrees `lat=36.7201600` and `lng=-4.4203400`.

* An optional part in which we can define more parameters in a pre-defined format.

  Example: the date can be specified in YYYY-MM-DD format `date=1990-05-22`, or in a relative format, such as “today” and “tomorrow”. If no date is specified, the default date will be today.

In [48]:
requests.get("https://api.sunrisesunset.io/json?lat=38.907192&lng=-77.036873").json()

{'results': {'date': '2025-08-11',
  'sunrise': '6:19:33 AM',
  'sunset': '8:09:49 PM',
  'first_light': '4:38:23 AM',
  'last_light': '9:50:59 PM',
  'dawn': '5:50:45 AM',
  'dusk': '8:38:37 PM',
  'solar_noon': '1:14:41 PM',
  'golden_hour': '7:32:58 PM',
  'day_length': '13:50:16',
  'timezone': 'America/New_York',
  'utc_offset': -240},
 'status': 'OK'}

In [49]:
# Get the sunrise and sunset times for Berlin.
# First define the latitude, longitude and date.
latitude = 52.52
longitude = 13.24
date = "2023-01-01"

# Combine the different parts from above to create one url.
sun = requests.get(f"https://api.sunrise-sunset.org/json?lat={latitude}&lng={longitude}&date={date}")
sun_json = sun.json()
sun_json

{'results': {'sunrise': '7:15:34 AM',
  'sunset': '3:05:22 PM',
  'solar_noon': '11:10:28 AM',
  'day_length': '07:49:48',
  'civil_twilight_begin': '6:36:35 AM',
  'civil_twilight_end': '3:44:21 PM',
  'nautical_twilight_begin': '5:52:30 AM',
  'nautical_twilight_end': '4:28:26 PM',
  'astronomical_twilight_begin': '5:10:54 AM',
  'astronomical_twilight_end': '5:10:02 PM'},
 'status': 'OK',
 'tzid': 'UTC'}

Let's access a few values from the JSON.

Notice that the JSON is enclosed in curly brackets `{}`. This means that it is a dictionary and we can access the values by calling their respecitve keys.

In [50]:
# Which are the keys?
sun_json.keys()

dict_keys(['results', 'status', 'tzid'])

In [51]:
# What is the value of the results key?
sun_json["results"]

{'sunrise': '7:15:34 AM',
 'sunset': '3:05:22 PM',
 'solar_noon': '11:10:28 AM',
 'day_length': '07:49:48',
 'civil_twilight_begin': '6:36:35 AM',
 'civil_twilight_end': '3:44:21 PM',
 'nautical_twilight_begin': '5:52:30 AM',
 'nautical_twilight_end': '4:28:26 PM',
 'astronomical_twilight_begin': '5:10:54 AM',
 'astronomical_twilight_end': '5:10:02 PM'}

In [52]:
# What is the time of the sunrise?
sun_json["results"]["sunrise"]

'7:15:34 AM'

### 3.3&nbsp; Transforming a JSON into a DataFrame

#### 3.3.1&nbsp;Option 1: pd.DataFrame()

In [53]:
sun_json

{'results': {'sunrise': '7:15:34 AM',
  'sunset': '3:05:22 PM',
  'solar_noon': '11:10:28 AM',
  'day_length': '07:49:48',
  'civil_twilight_begin': '6:36:35 AM',
  'civil_twilight_end': '3:44:21 PM',
  'nautical_twilight_begin': '5:52:30 AM',
  'nautical_twilight_end': '4:28:26 PM',
  'astronomical_twilight_begin': '5:10:54 AM',
  'astronomical_twilight_end': '5:10:02 PM'},
 'status': 'OK',
 'tzid': 'UTC'}

In [56]:
# Transform JSON into a DataFrame.
sun_df = pd.DataFrame(sun_json)
sun_df

                                 results status tzid
sunrise                       7:15:34 AM     OK  UTC
sunset                        3:05:22 PM     OK  UTC
solar_noon                   11:10:28 AM     OK  UTC
day_length                      07:49:48     OK  UTC
civil_twilight_begin          6:36:35 AM     OK  UTC
civil_twilight_end            3:44:21 PM     OK  UTC
nautical_twilight_begin       5:52:30 AM     OK  UTC
nautical_twilight_end         4:28:26 PM     OK  UTC
astronomical_twilight_begin   5:10:54 AM     OK  UTC
astronomical_twilight_end     5:10:02 PM     OK  UTC

This returns a DataFrame, and we could even set the indices using `.reset_index()`.

Still, we would prefer to have only a single row for a single day, with all the keys from the two different levels as column titles.

#### 3.3.2&nbsp;Option 2: pd.json_normalize()
Another way to handle nested dictionaries is by using json_normalize().

https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html

In [57]:
# Transform JSON into a DataFrame.
sun_norm = pd.json_normalize(sun_json)
sun_norm

,status,tzid,results.sunrise,results.sunset,results.solar_noon,results.day_length,results.civil_twilight_begin,results.civil_twilight_end,results.nautical_twilight_begin,results.nautical_twilight_end,results.astronomical_twilight_begin,results.astronomical_twilight_end
0,OK,UTC,7:15:34 AM,3:05:22 PM,11:10:28 AM,07:49:48,6:36:35 AM,3:44:21 PM,5:52:30 AM,4:28:26 PM,5:10:54 AM,5:10:02 PM

SUCCESS!

## 4.&nbsp; Creating DataFrames using for loops, lists and dictionaries

Often, there are several elements of the same type and structure inside one JSON. Let's have a look at an example and ask for the times for 3 days.

In [ ]:

https://api.sunrise-sunset.org/json?lat=52.52&lng=13.24&date=today

In [58]:
# Define the latitude, longitude and 3 days.
latitude = 52.52
longitude = 13.24
dates = ["yesterday", "today", "tomorrow"]

In [59]:
# Get the JSON for the first value inside the date lists (= yesterday).
sun = requests.get(f"https://api.sunrise-sunset.org/json?lat={latitude}&lng={longitude}&date={dates[2]}")
sun_json = sun.json()
sun_json

{'results': {'sunrise': '3:43:22 AM',
  'sunset': '6:40:44 PM',
  'solar_noon': '11:12:03 AM',
  'day_length': '14:57:22',
  'civil_twilight_begin': '3:06:03 AM',
  'civil_twilight_end': '7:18:03 PM',
  'nautical_twilight_begin': '2:14:54 AM',
  'nautical_twilight_end': '8:09:12 PM',
  'astronomical_twilight_begin': '1:10:10 AM',
  'astronomical_twilight_end': '9:13:56 PM'},
 'status': 'OK',
 'tzid': 'UTC'}

To get the times for all three days, we will use a for loop. It requests the data for yesterday first, then for today, then for tomorrow, and adds them as separate elements to a list.

The resulting list looks much like the JSON you get from APIs that provide the same type of data multiple times inside a single JSON. This step will therefore usually not be necessary because your initial JSON will already have a comparable structure.

If you like to review for loops and/or the range, here is some useful information:

- https://www.w3schools.com/python/python_for_loops.asp

- https://www.w3schools.com/python/ref_func_range.asp

In [60]:
dates

['yesterday', 'today', 'tomorrow']

In [61]:
# Initialize an empty list to store all the JSONs.
times = []
# Loop over the elements in the date list.
# Request data from the API for each of the date elements.
# Save the returned JSON in the time list.
for date in dates:
  times.append(requests.get(f"https://api.sunrise-sunset.org/json?lat={latitude}&lng={longitude}&date={date}").json())

In [62]:
times

[{'results': {'sunrise': '3:40:04 AM',
   'sunset': '6:44:42 PM',
   'solar_noon': '11:12:23 AM',
   'day_length': '15:04:38',
   'civil_twilight_begin': '3:02:18 AM',
   'civil_twilight_end': '7:22:27 PM',
   'nautical_twilight_begin': '2:10:12 AM',
   'nautical_twilight_end': '8:14:34 PM',
   'astronomical_twilight_begin': '1:02:48 AM',
   'astronomical_twilight_end': '9:21:58 PM'},
  'status': 'OK',
  'tzid': 'UTC'},
 {'results': {'sunrise': '3:41:43 AM',
   'sunset': '6:42:44 PM',
   'solar_noon': '11:12:13 AM',
   'day_length': '15:01:01',
   'civil_twilight_begin': '3:04:11 AM',
   'civil_twilight_end': '7:20:16 PM',
   'nautical_twilight_begin': '2:12:33 AM',
   'nautical_twilight_end': '8:11:53 PM',
   'astronomical_twilight_begin': '1:06:32 AM',
   'astronomical_twilight_end': '9:17:55 PM'},
  'status': 'OK',
  'tzid': 'UTC'},
 {'results': {'sunrise': '3:43:22 AM',
   'sunset': '6:40:44 PM',
   'solar_noon': '11:12:03 AM',
   'day_length': '14:57:22',
   'civil_twilight_begin': '3:06:03 AM',
   'civil_twilight_end': '7:18:03 PM',
   'nautical_twilight_begin': '2:14:54 AM',
   'nautical_twilight_end': '8:09:12 PM',
   'astronomical_twilight_begin': '1:10:10 AM',
   'astronomical_twilight_end': '9:13:56 PM'},
  'status': 'OK',
  'tzid': 'UTC'}]

If we only want to select certain parts of the JSON:
- Option 1: transform the entire JSON into a DataFrame and drop the rest.
- Option 2: Use a for loop to extract only the required information. This is what we will look into as the next step.

### 4.1&nbsp;Write a for loop

Creating a for loop is usually an iterative process.

First, we select one value from our JSON that we would like to have in our final DataFrame. Let's start with yesterday's sunrise time.

>To access values inside nested lists and dictionaries, we need to apply the [Matryoshka doll](https://en.wikipedia.org/wiki/Matryoshka_doll) principle. This means that we will need to access the most outer dictionary/list first, then the next one inside, then the next etc.

In [64]:
# First select the element of the list that contains yesterday's data.
# Then select the keys that navigate you to the sunrise time.
times[0]["results"]["sunrise"]

'3:40:04 AM'

In [ ]:
yesterday_sunrise = times[0]["results"]["sunrise"]

Using this code, it is easy to get the sunrise time of today and tomorrow, too. Just change the value to the index of the day you're interested in.

In [65]:
times[1]["results"]["sunrise"], times[2]["results"]["sunrise"]

('3:41:43 AM', '3:43:22 AM')

Now let's build a for loop with the code we have prepared:

In [66]:
# Create an empty list which will be filled with the sunrise times.
sunrise = []

# Iterate over the 3 dictionaries inside the times list.
for time in times:
  # For each day, get the sunrise time and append it to the sunrise list.
  sunrise.append(time["results"]["sunrise"])

In [67]:
# Let's have a look at the sunrise list.
sunrise

['3:40:04 AM', '3:41:43 AM', '3:43:22 AM']

SUCCESS!

Once this loop works with one value, more can be added. Let's add the sunset time and the day length.

In [68]:
# Create an empty list for each of the values.
sunrise = []
sunset = []
day_length = []

# Iterate over the 3 dictionaries inside the times list.
for time in times:
  # For each day, get the sunrise time and append it to the sunrise list.
  sunrise.append(time["results"]["sunrise"])
  # For each day, get the sunset time and append it to the sunset list.
  sunset.append(time["results"]["sunset"])
  # For each day, get the day length and append it to the day length list.
  day_length.append(time["results"]["day_length"])

Let's have a look at all these lists.

In [69]:
sunrise, sunset, day_length

(['3:40:04 AM', '3:41:43 AM', '3:43:22 AM'],
 ['6:44:42 PM', '6:42:44 PM', '6:40:44 PM'],
 ['15:04:38', '15:01:01', '14:57:22'])

### 4.2&nbsp;Create a DataFrame using lists

As a final step, we want to merge these lists into a DataFrame.

In [70]:
# Zip the different lists, and add the column labels at the end.
times_df = pd.DataFrame(list(zip(sunrise, sunset, day_length)), columns=["Sunrise", "Sunset", "Day_length"])
times_df

      Sunrise      Sunset Day_length
0  3:40:04 AM  6:44:42 PM   15:04:38
1  3:41:43 AM  6:42:44 PM   15:01:01
2  3:43:22 AM  6:40:44 PM   14:57:22

### 4.3&nbsp;Create a DataFrame using dictionaries

Alternatively, a dataframe can be created from a dictionary, using the lists from the for loop above.

In [71]:
# Pass a dictionary inside pd.DataFrame().
# Its keys are the column labels.
# Its values are the lists containing the data to become the columns of your DataFrame.
# We can even easily add the list containing the dates.
times_df_dictionary = pd.DataFrame({"Day": dates,
                                    "Sunrise": sunrise,
                                    "Sunset": sunset,
                                    "Day length": day_length}
                                   )
times_df_dictionary

         Day     Sunrise      Sunset Day length
0  yesterday  3:40:04 AM  6:44:42 PM   15:04:38
1      today  3:41:43 AM  6:42:44 PM   15:01:01
2   tomorrow  3:43:22 AM  6:40:44 PM   14:57:22

Another option is to create the dictionary first, and then use the for loop to fill its values.

In [ ]:
# Create an empty list for each of the values.
times_dictionary = {"Sunrise": [],
                    "Sunset": [],
                    "Day_length": []}

# Iterate over the 3 dictionaries inside the times list.
for time in times:
  # For each day, get the sunrise time and append it to the sunrise list.
  times_dictionary["Sunrise"].append(time["results"]["sunrise"])
  # For each day, get the sunset time and append it to the sunset list.
  times_dictionary["Sunset"].append(time["results"]["sunset"])
  # For each day, get the day length and append it to the day length list.
  times_dictionary["Day_length"].append(time["results"]["day_length"])

times_dictionary

{'Sunrise': ['6:00:40 AM', '6:02:30 AM', '6:04:20 AM'],
 'Sunset': ['3:40:35 PM', '3:38:43 PM', '3:36:51 PM'],
 'Day_length': ['09:39:55', '09:36:13', '09:32:31']}

In [ ]:
# Create a DataFrame from the dictionary.
times_dictionary_df = pd.DataFrame(times_dictionary)
times_dictionary_df

      Sunrise      Sunset Day_length
0  6:00:40 AM  3:40:35 PM   09:39:55
1  6:02:30 AM  3:38:43 PM   09:36:13
2  6:04:20 AM  3:36:51 PM   09:32:31

## 5.&nbsp;APIs with keys

Some APIs restrict access to their data in the sense that users need to register beforehand. Upon registration, users receive an API key that is linked to their account. This has two main consequences:

* The url used to request the data needs to contain the API key.
* The API can track the number and type of requests made. This enables APIs to limit the number of requests per account within a certain timeframe.

Let's have a look at how this works with an API that provides some statistics on AirQuality in cities around the world: https://api-ninjas.com/api/airquality

There are a few parameters required to filter the cities returned. We will use these:
* lat (required) - latitude of the city
* lon (required) - longitude of the city
* country (optional) - country filter. Must be an ISO-3166 alpha-2 country code (e.g. US).

### 5.1&nbsp;Accessing the data

In [72]:
# Define the parameters to be passed into the url. We want to see the ar
country = "DE"
lat = 53.99
lon = 10.68 
API_key = "qClItv2fg4hGDiVLf6zTNw==rLE3xLfQa0uwZFD0"

# Reference the parameters in the url.
schwartau_air = requests.get(f"https://api.api-ninjas.com/v1/airquality?lat={lat}&lon={lon}&country={country}", headers={'X-Api-Key': API_key})
schwartau_json = schwartau_air.json()
schwartau_json

{'CO': {'concentration': 140.99, 'aqi': 1},
 'NO2': {'concentration': 0.76, 'aqi': 0},
 'O3': {'concentration': 92.41, 'aqi': 143},
 'SO2': {'concentration': 1.02, 'aqi': 1},
 'PM2.5': {'concentration': 3.03, 'aqi': 9},
 'PM10': {'concentration': 6.49, 'aqi': 6},
 'overall_aqi': 143}

In [73]:
# Or define the sections that will together form the url.
url = "https://api.api-ninjas.com/v1/airquality"
header={"X-Api-Key": "qClItv2fg4hGDiVLf6zTNw==rLE3xLfQa0uwZFD0"}
querystring = {"lat": 53.99, "lon": 10.68, "country": "DE", }

# Reference the sections in the request.
# schwartau_air = requests.request("GET", url, headers=header, params=querystring)
schwartau_air = requests.get(url, headers=header, params=querystring)
schwartau_json = schwartau_air.json()
schwartau_json

{'CO': {'concentration': 140.99, 'aqi': 1},
 'NO2': {'concentration': 0.76, 'aqi': 0},
 'O3': {'concentration': 92.41, 'aqi': 143},
 'SO2': {'concentration': 1.02, 'aqi': 1},
 'PM2.5': {'concentration': 3.03, 'aqi': 9},
 'PM10': {'concentration': 6.49, 'aqi': 6},
 'overall_aqi': 143}

### 5.2&nbsp;Transforming the data

Create a dataframe that contains the information from the JSON.

In [74]:
schwartau_df = pd.DataFrame(schwartau_json)
schwartau_df

                   CO   NO2      O3   SO2  PM2.5  PM10  overall_aqi
concentration  140.99  0.76   92.41  1.02   3.03  6.49          143
aqi              1.00  0.00  143.00  1.00   9.00  6.00          143